name: Nightly

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  compile:
    name: Gradle compiler
    runs-on: ubuntu-latest
    steps:

    # 1. Check out the current working tree
    - name: Checkout repository
      uses: actions/checkout@v2

    # 2. Setup Java 17 JDK (Adopt)
    - name: Java 17 setup
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-package: jdk
        java-version: '17'

    # 3. Build via Gradle 
    - name: Build via Gradle
      run: ./gradlew clean build

    # 4. Upload artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        path: /home/runner/work/PlotSquared/PlotSquared/
